# Generated by Django 4.1.7 on 2023-02-17 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_field', models.CharField(blank=True, max_length=2000)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.section')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=2000)),
                ('skills', models.CharField(blank=True, max_length=2000)),
                ('aoi', models.CharField(blank=True, max_length=2000)),
                ('github', models.CharField(blank=True, max_length=2000)),
                ('linkedin', models.CharField(blank=True, max_length=2000)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.section')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test1', models.CharField(blank=True, max_length=2000)),
                ('test2', models.CharField(blank=True, max_length=2000)),
                ('test3', models.CharField(blank=True, max_length=2000)),
                ('test1d', models.ImageField(blank=True, upload_to='plots')),
                ('test2d', models.ImageField(blank=True, upload_to='plots')),
                ('test3d', models.ImageField(blank=True, upload_to='plots')),
                ('test1pd', models.ImageField(blank=True, upload_to='plots')),
                ('test2pd', models.ImageField(blank=True, upload_to='plots')),
                ('test3pd', models.ImageField(blank=True, upload_to='plots')),
                ('test1p', models.ImageField(blank=True, upload_to='plots')),
                ('test2p', models.ImageField(blank=True, upload_to='plots')),
                ('test3p', models.ImageField(blank=True, upload_to='plots')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_field', models.CharField(blank=True, max_length=2000)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.questions')),
            ],
        ),
    ]
